content:
  - name: posts
    label: Posts
    type: collection
    path: 'src/content/blog'
    fields:
      - name: title
        label: Title
        type: string
      - name: body
        label: Body
        type: rich-text